### ISSUE TITLE
Question about compiler version pinning

### ISSUE THREAD

**Issue by danpetry** [conda-forge/cuda-nvcc-impl-feedstock#14]
### Comment:

Is there any reason that you need to use gcc v12 specifically? It's used to compile with nvcc for a test - it looks like [a wider range](https://docs.nvidia.com/cuda/archive/12.3.0/cuda-installation-guide-linux/index.html#host-compiler-support-policy) is compatible in general.

Also, just wondering why is `{{ compiler("c") }}` a build dep for some of the subpackages? It doesn't look like anything's being compiled for these.

Thanks :)

**Comment by danpetry** [comment]
Also the strict pinning on the visual studio build for that same test?

**Comment by jakirkham** [comment]
The runtime constraints on the compiler themselves are fairly lax. These line up with the version support recommended for [Linux]( https://docs.nvidia.com/cuda/archive/12.3.0/cuda-installation-guide-linux/index.html#host-compiler-support-policy ) and [Windows]( https://docs.nvidia.com/cuda/archive/12.3.0/cuda-installation-guide-microsoft-windows/index.html#system-requirements )

https://github.com/conda-forge/cuda-nvcc-impl-feedstock/blob/45b155617aa7e55f34e2dfd1d22405cf5a4e5139/recipe/meta.yaml#L148-L151

https://github.com/conda-forge/cuda-nvcc-impl-feedstock/blob/45b155617aa7e55f34e2dfd1d22405cf5a4e5139/recipe/conda_build_config.yaml#L7-L12

Though one note with Windows. Visual Studio 2017 is noted as a supported version. However we ran into issues with that Visual Studio version ( https://github.com/conda-forge/cuda-nvcc-impl-feedstock/pull/5#discussion_r1358905317 ) and conda-forge dropped support for it some time ago ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3167 ). So we just made Visual Studio 2019 the minimum

<hr>

We don't actually pin [the C or C++ compilers during tests]( https://github.com/conda-forge/cuda-nvcc-impl-feedstock/blob/45b155617aa7e55f34e2dfd1d22405cf5a4e5139/recipe/meta.yaml#L152-L157 ) (with the exception of Windows noted before). When using the `{{ compiler("c") }}` or  `{{ compiler("cxx") }}` syntax. Instead Conda-Build looks for `c*_compiler` and `c*_compiler_version` in the recipe or any of the variants. In conda-forge specifically we have some global variants in `conda-forge-pinning`, these will be used to [determine the compilers]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/bcdbfce46f9ad65ccf507294347cebb583450b03/recipe/conda_build_config.yaml#L1-L20 ) (if the recipe doesn't override it somehow). We are content to test with the same compilers that conda-forge specifies in the global pinnings as that provides us a good indication of whether NVCC will work well in the conda-forge build toolchain

**Comment by danpetry** [comment]
ok, thanks. But what I meant about the compiler was: why are the compilers a build dep? Nothing's being compiled, is it? This is just binary repackaging. Or what am I missing..?

**Comment by danpetry** [comment]
Is this so conda-build can do linkage checks?

**Comment by jakirkham** [comment]
Sorry for missing the follow-up question

As elsewhere this is to ensure that the `run_exports` are captured as dependencies of these packages (like `libgcc`). In this case it involves compilers, but other packages also do this with libraries

Also yes this will fix linkage check issues. Though it is worth pointing out that the linkage check issues are valid, so we do want the `run_exports` to fix them

**Comment by danpetry** [comment]
thanks, closed as answered
