### ISSUE TITLE
Do you need to symlink ar for linux-aarch64?

### ISSUE THREAD

**Issue by danpetry** [conda-forge/cuda-nvcc-impl-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

While building this for defaults, we had to add this ar symlink (the gcc/g++ stuff is simply to replace your `gcc` and `gxx` packages):
https://github.com/AnacondaRecipes/cuda-nvcc-impl-feedstock/pull/1/commits/16af201eecef27806d9772a4af06c941734001b9
to make the cmake tests find ar properly on linux-aarch64.
I'm putting this in an issue rather than a commit since a) I don't know your plans to build arm linux and b) I don't know your ecosystem or build platform so it might not be needed.

### Installed packages

```shell
n/a
```

### Environment info

```shell
anaconda CI
```

**Comment by jakirkham** [comment]
Not that I'm aware of (unless something is doing that under-the-hood)

This seems like a bug somewhere

Could you please share a bit more about how this comes up for you?

**Comment by danpetry** [comment]
Hmm this was so long ago I can't remember what happened, and we don't have the logs. It looks like cmake can't find ar properly while running cmake's cuda tests for nvcc-impl.

This looks like either a CMake bug or maybe some way we're handling ar with our CMake files. Can close as it doesn't seem relevant to you anyway and give you a heads-up if we revisit it.
